services:
  frontend:
    restart: always
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "1337:80"
    depends_on:
      - backend
      
  backend:
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    expose:
      - "3000"